### ISSUE TITLE
deer-refresh:zle:58: can only be called from widget function

### ISSUE THREAD

**Issue by anoduck** [vifon/deer#32] opened 2020-08-03 14:48 UTC
Installed with antigen, generates error everytime I attempt to run the program.  
```deer-refresh:zle:58: can only be called from widget function```
Not sure how to debug this error or provide more information than the above. Let me know if I can be of anymore assisstance.

**Comment by vifon** [comment] 2020-08-04 14:38
How do you run it?

**Comment by anoduck** [comment] 2020-08-04 19:42
Ah, I see what you are saying...the error might be coming from how I run deer in the terminal.  
Since I use antigen to manage my shell plugins and addons I have the following in my zshrc.  
```zsh
antigen bundle Vifon/deer
# source $HOME/.antigen/bundles/Vifon/deer/deer
autoload -U deer
zle -N deer
bindkey '\ek' deer
```  
When I desire to run deer. I type deer in the terminal prompt like so: `# deer`.  The key code '\ek'(alt-k) does not work.

**Comment by vifon** [comment] 2020-08-05 12:07
`deer` must be invoked with a keybinding, it won't work when called like this. Maybe something is overwriting your keybindings?

**Comment by anoduck** [comment] 2020-08-08 08:31
Oh, fiddlesticks! This is likely the issue. Have any suggestions for a keybinding? `'^[y'` is not working.

**Comment by vifon** [comment] 2020-08-08 15:14
I'd start with disabling all the other large parts of your config to pin down the cause.

I'll close the issue as it's not a problem with deer but we can continue the discussion if you need further help.

**Closed by vifon** 2020-08-08 15:14 UTC
